name: widgetbook_workspace # cannot be named just "widgetbook"
description: A playground to streamline shared_ui with Widgetbook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_ui:
    path: ../packages/shared_ui
  widgetbook:
    path: ../../../packages/widgetbook

dev_dependencies:
  build_runner: ^2.6.1
  widgetbook_generator:
    path: ../../../packages/widgetbook_generator
dependency_overrides:
  meta: ^1.16.0

flutter:
  uses-material-design: true
