name: widgetbook_generator
description: A package to automate setup and maintenance of the widgetbook package by using code generation.
version: 4.0.0-alpha.2
homepage: https://www.widgetbook.io?utm_source=pub.dev&utm_medium=link&utm_campaign=widgetbook_generator
repository: https://github.com/widgetbook/widgetbook/tree/main/packages/widgetbook_generator
issue_tracker: https://github.com/widgetbook/widgetbook/issues
documentation: https://docs.widgetbook.io
topics: [widgetbook, storybook, ui, codegen, build-runner]

screenshots:
  - description: 'Widgetbook Logo'
    path: assets/logo.png

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ^7.7.1
  build: ^3.0.1
  code_builder: ^4.8.0
  collection: ^1.15.0
  crypto: ^3.0.0
  glob: ^2.1.0
  meta: ^1.7.0
  path: ^1.8.0
  source_gen: ^3.0.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.24.0
